apiVersion: apps/v1
kind: Deployment
metadata:
  name: "frontend-deployment"
  namespace: "sample-node"
spec:
  selector:
    matchLabels:
      app: "frontend"
  replicas: 1
  template:
    metadata:
      labels:
        app: "frontend"
    spec:
      containers:
      - image: cr.eu-north1.nebius.cloud/e00nwcbe73nn4yhzvn/node-sample:latest
        imagePullPolicy: Always
        name: "frontend"
        ports:
        - containerPort: 80
